<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://packtpub.com/service/employee/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:WL5G3N1="http://packtpub.com/service/employee/"
    >
    <plnk:partnerLinkType name="employeeLT">
        <plnk:role name="employeeTravelStatusService">
            <plnk:portType name="WL5G3N1:EmployeeTravelStatusPT"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://packtpub.com/service/employee/" location="orauddi:/uddi:bea.com:servicebus:TravelApproval:ProxyServices:EmployeeTravelStatusServiceProxy"/>
</wsdl:definitions>
