<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="http://localhost:8001/soa-infra/services/default/AmericanAirlines/Airline.wsdl"/>
      <rootElement name="confirmationData" namespace="http://packtpub.com/service/airline/"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/BAMServConn_TravelApproval_SELECTED_TICKETS.xsd"/>
      <rootElement name="_SELECTED_TICKETSCollection" namespace="http://xmlns.oracle.com/bam"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.3.0(build 100415.2045.2557) AT [SAT JUN 26 09:26:48 CEST 2010]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel2="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns1="http://xmlns.oracle.com/bam"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://packtpub.com/service/employee/"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://packtpub.com/service/airline/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 soap12 soap mime tns xsd ns1 xp20 bpws bpel2 bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns1:_SELECTED_TICKETSCollection>
      <ns1:_SELECTED_TICKETS>
        <ns1:_FlightNo>
          <xsl:value-of select="/tns:confirmationData/FlightNo"/>
        </ns1:_FlightNo>
        <ns1:_Airline>
          <xsl:text disable-output-escaping="no">Delta</xsl:text>
        </ns1:_Airline>
        <ns1:_TravelClass>
          <xsl:value-of select="/tns:confirmationData/TravelClass"/>
        </ns1:_TravelClass>
        <ns1:_Price>
          <xsl:value-of select="/tns:confirmationData/Price"/>
        </ns1:_Price>
        <ns1:_DepartureDateTime>
          <xsl:value-of select="/tns:confirmationData/DepartureDateTime"/>
        </ns1:_DepartureDateTime>
        <ns1:_ReturnDataTime>
          <xsl:value-of select="/tns:confirmationData/ReturnDateTime"/>
        </ns1:_ReturnDataTime>
      </ns1:_SELECTED_TICKETS>
    </ns1:_SELECTED_TICKETSCollection>
  </xsl:template>
</xsl:stylesheet>
