<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://packtpub.com/bpel/travel/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:aln="http://packtpub.com/service/airline/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="http://packtpub.com/bpel/travel/">
	<import namespace="http://packtpub.com/service/airline/" location="Airline.wsdl"/>
	<types>
		<xsd:schema targetNamespace="http://packtpub.com/bpel/travel/types" elementFormDefault="qualified"/>
		<xsd:schema>
			<xsd:import schemaLocation="xsd/TravelRequestType.xsd" namespace="http://packtpub.com/bpel/travel/"/>
		</xsd:schema>
	</types>
	<message name="TravelRequestMessage">
		<part name="travelRequest" element="tns:TravelApproval"/>
	</message>
	<portType name="TravelApprovalPT">
		<operation name="TravelApproval">
			<input message="tns:TravelRequestMessage"/>
		</operation>
	</portType>
	
  <portType name="ClientCallbackPT">
		<operation name="ClientCallback">
			<input message="aln:ReservationResponseMessage"/>
		</operation>
	</portType>	
	
</definitions>
